name: My CI-CD 
on:
  push: 
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: pwd
      - run: ls -alh
      - run: sudo ls -alh
      - run: which which
      - run: curl -L https://nixos.org/nix/install | sh
      - run: true
