name: My CI-CD 
on:
  push: 
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: curl -L https://nixos.org/nix/install | sh
      - run: . /home/runner/.nix-profile/etc/profile.d/nix.sh
      - run: pwd
      - run: cd tests
      - run: pwd
      - run:  . /home/runner/.nix-profile/etc/profile.d/nix.sh && cd tests && nix develop --extra-experimental-features --command hello
