name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        access-tokens = gitub.com=${{ secrets.TOKEN }}
    - name: Build release
      run: cd tests/positive && nix develop --command hello build --release
