name: "Test"
on:
  pull_request:
  push:
jobs:
  positives:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.TOKEN }}
    - run: cd util/test-positives && nix develop --command test
  versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.TOKEN }}
    - run: cd util/test-versions && nix develop --command test
