name: "Test"
on:
  pull_request:
  push:
jobs:
  negatives:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.TOKEN }}
    - run: cd util/test-negatives && ( nix develop --command check || cat /nix/store/nhkxg3ajn6f67wfd17p82k1dmk666qd1-sad1 )
  positives:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.TOKEN }}
    - run: cd util/test-positives && nix develop --command check
  versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.TOKEN }}
    - run: cd util/test-versions && nix develop --command check
