name: "Test"
on:
  pull_request:
jobs:
  _negatives:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.TOKEN }}
    - run: cd util/test-negatives && nix develop --command check
  _positives:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.TOKEN }}
    - run: cd util/test-positives && nix develop --command check
  _versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.TOKEN }}
    - run: cd util/test-versions && nix develop --command check
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cat flake.lock | jq --raw-output ".nodes"

