name: "Update"
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.TOKEN }}
    - name: Build release
      run: cd versions && nix develop --command hook
